version: '3'
services:
  config-server:
    image: springcloud/configserver
    ports:
      - "8888:8888"
    networks:
      - api-network
  eureka-server:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    networks:
      - api-network

  customer-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_CUSTOMER_USERNAME}
      POSTGRES_PASSWORD: ${DB_CUSTOMER_PASSWORD}
      POSTGRES_DB: ${DB_CUSTOMER_DBNAME}
    volumes:
      - customer-service-data:/var/lib/postgresql/data
    networks:
      - api-network
    restart: always

  customer-service:
    ports:
      - "8080:8080"
    build:
      context: ./customer-service
    depends_on:
      - customer-db




volumes:
  customer-service-data:
networks:
  api-network:
    driver: bridge


